spring.application.name=AI

gemini.api.key=AIzaSyCwLavLexW9-v8744VfyyUjxLYVjpn792w
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${gemini.api.key}